src/main/resources/static/css/chartpage_main.css, src/main/resources/static/css/community_detail.css, src/main/resources/static/css/login_join.css, src/main/resources/static/css/login_login.css, src/main/resources/static/css/membership_join.css, src/main/resources/static/css/mypage_user.css, src/main/resources/static/css/nav.css, src/main/resources/static/css/playlist_mine.css, src/main/resources/static/css/playlist_public.css, src/main/resources/templates/community_detail.html, src/main/resources/templates/login_join.html
=> community_detail

src/main/resources/static/css/login_join.css, src/main/resources/templates/login_join.html
=> keyword_search

src/main/resources/static/js/sociallogin_naver.js, src/main/resources/templates/login_join.html, src/main/resources/templates/login_login.html
=> jquery_search

src/main/java/com/multi/fourtunes/model/biz/LoginBiz.java, src/main/java/com/multi/fourtunes/model/biz/LoginBizImple.java, src/main/java/com/multi/fourtunes/model/biz/UserBizImpl.java, src/main/java/com/multi/fourtunes/model/controller/LoginController.java
=> facebook 완

src/main/java/com/multi/fourtunes/model/biz/LoginBizImple.java, src/main/java/com/multi/fourtunes/model/controller/LoginController.java, src/main/java/com/multi/fourtunes/model/dao/UserDaoImpl.java, src/main/resources/templates/login_login.html
UserBiz, UserController 따로 작성되어있던 코드들 Login에 합침
=> Code Refactoring

src/main/java/com/multi/fourtunes/model/biz/LoginBizImple.java, src/main/java/com/multi/fourtunes/model/controller/LoginController.java, src/main/resources/templates/login_join.html
=> Jung min insert user

src/main/java/com/multi/fourtunes/model/biz/KeywordBiz.java, src/main/java/com/multi/fourtunes/model/biz/KeywordBizImpl.java, src/main/java/com/multi/fourtunes/model/biz/LoginBiz.java, src/main/java/com/multi/fourtunes/model/biz/LoginBizImple.java, src/main/java/com/multi/fourtunes/model/controller/LoginController.java, src/main/java/com/multi/fourtunes/model/dao/KeywordDao.java, src/main/java/com/multi/fourtunes/model/dao/UserDao.java, src/main/java/com/multi/fourtunes/model/dao/UserDaoImpl.java, src/main/java/com/multi/fourtunes/model/dao/keywordDaoImple.java, src/main/java/com/multi/fourtunes/model/mapper/KeywordMapper.java, src/main/java/com/multi/fourtunes/model/mapper/UserMapper.java, src/main/resources/templates/login_join.html, src/main/resources/templates/login_socialjoin.html
=> InsertUser(general, social)

src/main/java/com/multi/fourtunes/model/biz/CommunityBiz.java, src/main/java/com/multi/fourtunes/model/biz/CommunityBizImpl.java, src/main/java/com/multi/fourtunes/model/controller/CommunityController.java, src/main/java/com/multi/fourtunes/model/dao/CommunityDao.java, src/main/java/com/multi/fourtunes/model/dao/CommunityDaoImpl.java, src/main/java/com/multi/fourtunes/model/dto/CommunityDto.java, src/main/java/com/multi/fourtunes/model/mapper/CommunityMapper.java, src/main/resources/templates/community_detail.html, src/main/resources/templates/community_list.html
이름 받아오기, 조회수 카운트, 글 최신순으로 보여주기
=> Yunji commu

src/main/java/com/multi/fourtunes/model/controller/CommunityController.java, src/main/java/com/multi/fourtunes/model/controller/LoginController.java, src/main/java/com/multi/fourtunes/model/mapper/CommunityMapper.java, src/main/resources/templates/community_write.html
=> Jihoon crud write

src/main/java/com/multi/fourtunes/model/controller/LoginController.java, src/main/resources/static/css/login_login.css, src/main/resources/static/js/sociallogin_kakao.js, src/main/resources/templates/login_login.html
=> Minsu kakao

src/main/resources/templates/mypage_community.html
=> 글자 깨지는거 수정

src/main/java/com/multi/fourtunes/model/mapper/CommunityMapper.java
=> 상세 페이지 글 순서

src/main/java/com/multi/fourtunes/model/biz/AdminpageBizImpl.java, src/main/java/com/multi/fourtunes/model/controller/AdminpageController.java, src/main/java/com/multi/fourtunes/model/dao/ReportDao.java, src/main/java/com/multi/fourtunes/model/dao/ReportDaoImpl.java, src/main/java/com/multi/fourtunes/model/dto/AdminCommentReportDto.java, src/main/java/com/multi/fourtunes/model/dto/AdminCommunityReportDto.java, src/main/java/com/multi/fourtunes/model/mapper/ReportMapper.java, src/main/resources/static/css/adminpage_comment.css, src/main/resources/static/css/adminpage_community.css, src/main/resources/static/css/adminpage_user.css, src/main/resources/templates/adminpage_comment.html, src/main/resources/templates/adminpage_community.html, src/main/resources/templates/adminpage_user.html
Adminpage 신고 게시글, 신고 댓글 관리 구현 완료
=> Adminpage 구현 완료

src/main/resources/static/css/community_detail.css, src/main/resources/static/css/community_list.css, src/main/resources/templates/community_detail.html
=> 디테일 페이지 css 수정

src/main/resources/static/css/adminpage_comment.css, src/main/resources/static/css/adminpage_community.css, src/main/resources/static/css/adminpage_user.css, src/main/resources/static/css/mypage_community.css, src/main/resources/static/css/nav.css, src/main/resources/templates/adminpage_comment.html, src/main/resources/templates/adminpage_community.html, src/main/resources/templates/adminpage_searchuser.html, src/main/resources/templates/adminpage_user.html, src/main/resources/templates/mypage_community.html, src/main/resources/templates/mypage_user.html
=> Adminpage, Mypage CSS 수정

src/main/java/com/multi/fourtunes/model/controller/CommunityController.java, src/main/resources/templates/community_detail.html
=> Yunji alert

src/main/resources/templates/adminpage_user.html
관리자 페이지에서 회원 탈퇴 처리 시, 경고창 뜨도록 변경함
=> Adminpage DeleteUser Alert 생성

src/main/resources/static/css/community_detail.css, src/main/resources/templates/community_detail.html
=> 디테일 페이지 css

src/main/java/com/multi/fourtunes/model/biz/LoginBiz.java, src/main/java/com/multi/fourtunes/model/biz/LoginBizImple.java, src/main/java/com/multi/fourtunes/model/controller/KakaopayController.java, src/main/java/com/multi/fourtunes/model/controller/NavController.java, src/main/java/com/multi/fourtunes/model/controller/paging/InnerPagingController.java, src/main/java/com/multi/fourtunes/model/dao/PayDao.java, src/main/java/com/multi/fourtunes/model/dao/PayDaoImpl.java, src/main/java/com/multi/fourtunes/model/mapper/PayMapper.java, src/main/resources/templates/mypage_user.html
결제시 마이페이지에 회원등급 출력되도록 구현
결제개월수 조회하여 만료일 출력되도록 구현
=> Mypage UserGradeUpdate

src/main/java/com/multi/fourtunes/model/biz/PlaylistBiz.java, src/main/java/com/multi/fourtunes/model/biz/PlaylistBizImple.java, src/main/java/com/multi/fourtunes/model/controller/LoginController.java, src/main/java/com/multi/fourtunes/model/dao/PlayListDaoImple.java, src/main/java/com/multi/fourtunes/model/dao/PlaylistDao.java, src/main/java/com/multi/fourtunes/model/mapper/ManageSongMapper.java, src/main/java/com/multi/fourtunes/model/mapper/PlayListMapper.java
=> Jms join playlist add

src/main/java/com/multi/fourtunes/model/controller/CommunityController.java, src/main/resources/templates/community_detail.html
=> 신고 alert 창 구현 완료

src/main/java/com/multi/fourtunes/model/biz/PlaylistBiz.java, src/main/java/com/multi/fourtunes/model/biz/PlaylistBizImple.java, src/main/java/com/multi/fourtunes/model/controller/PlayListController.java, src/main/java/com/multi/fourtunes/model/dto/PlaylistDto.java, src/main/java/com/multi/fourtunes/model/mapper/PlayListMapper.java, src/main/resources/static/css/main.css, src/main/resources/templates/index.html
=> Jihoon index jquery

src/main/java/com/multi/fourtunes/intercepter/SessionInvalidationInterceptor.java, src/main/java/com/multi/fourtunes/model/configuration/WebConfig.java, src/main/resources/templates/adminpage_user.html
Session에 login 객체 없을때마다, Session Invalidate하기
=> Session에 login 객체 없을때마다, Session Invalidate하기

src/main/java/com/multi/fourtunes/model/biz/LoginBiz.java, src/main/java/com/multi/fourtunes/model/biz/LoginBizImple.java, src/main/java/com/multi/fourtunes/model/controller/LoginController.java, src/main/resources/static/css/login_join.css, src/main/resources/templates/login_join.html
ID 중복확인 및, 정규표현식을 통한 Email값 작성 유도
=> 회원가입시 email 확인

src/main/java/com/multi/fourtunes/model/apis/YoutubeApi.java, src/main/java/com/multi/fourtunes/model/biz/SuggestBizImpl.java, src/main/java/com/multi/fourtunes/model/controller/SearchController.java
=> Jung min youtube api error handler

src/main/java/com/multi/fourtunes/Application.java, src/main/java/com/multi/fourtunes/model/batch/SuggestCountResseter.java, src/main/java/com/multi/fourtunes/model/biz/SuggestBiz.java, src/main/java/com/multi/fourtunes/model/biz/SuggestBizImpl.java, src/main/java/com/multi/fourtunes/model/configuration/WebConfig.java, src/main/java/com/multi/fourtunes/model/controller/NavController.java, src/main/java/com/multi/fourtunes/model/dao/UserDao.java, src/main/java/com/multi/fourtunes/model/dao/UserDaoImpl.java, src/main/java/com/multi/fourtunes/model/mapper/UserMapper.java
=> Jung min membership benefit

src/main/java/com/multi/fourtunes/model/biz/PlaylistBiz.java, src/main/java/com/multi/fourtunes/model/biz/PlaylistBizImple.java, src/main/java/com/multi/fourtunes/model/controller/PlayListController.java, src/main/java/com/multi/fourtunes/model/dto/SongDto.java, src/main/resources/static/js/infinitescroll.js, src/main/resources/templates/playlist_mine.html, src/main/resources/templates/playlist_public.html
1. 초기 Public 혹은 Mine 플레이리스트 접근시, 보여줄 노래의 List 를 Session에 저장
2. 무한스크롤 로딩이 필요할 때마다, List에서 8개씩 꺼내와서 프론트에 전달
3. Ajax success 함수에서, Dom 생성 후 append
=> Duo infinite scroll

src/main/java/com/multi/fourtunes/model/biz/AdminpageBizImpl.java, src/main/java/com/multi/fourtunes/model/biz/PlaylistBizImple.java
=> AIKEYWORD 관리자 페이지

src/main/java/com/multi/fourtunes/model/apis/AnalysisApi.java, src/main/java/com/multi/fourtunes/model/batch/SuggestCountResseter.java, src/main/java/com/multi/fourtunes/model/biz/AnalysisBiz.java, src/main/java/com/multi/fourtunes/model/biz/AnalysisBizImpl.java, src/main/java/com/multi/fourtunes/model/biz/PlaylistBizImple.java, src/main/java/com/multi/fourtunes/model/jpa/repository/SongRepository.java, src/main/resources/static/css/mypage_analysis.css, src/main/resources/templates/mypage_analysis.html, src/main/resources/templates/mypage_user.html
=> Yunji analysis css

src/main/resources/static/css/mypage_analysis.css, src/main/resources/static/css/mypage_community.css
=> mypage css 수정

src/main/java/com/multi/fourtunes/model/apis/AnalysisApi.java, src/main/java/com/multi/fourtunes/model/apis/ApiTestController.java, src/main/java/com/multi/fourtunes/model/apis/ApiTestRestController.java, src/main/java/com/multi/fourtunes/model/apis/ApiTestService.java, src/main/java/com/multi/fourtunes/model/apis/ManiaDbApi.java, src/main/java/com/multi/fourtunes/model/apis/OpenAiApi.java, src/main/java/com/multi/fourtunes/model/apis/YoutubeApi.java, src/main/java/com/multi/fourtunes/model/batch/GlobalBatch.java, src/main/java/com/multi/fourtunes/model/biz/AdminpageBizImpl.java, src/main/java/com/multi/fourtunes/model/biz/CommunityBizImpl.java, src/main/java/com/multi/fourtunes/model/biz/LoginBizImple.java, src/main/java/com/multi/fourtunes/model/biz/PlaylistBizImple.java, src/main/java/com/multi/fourtunes/model/biz/SuggestBizImpl.java, src/main/java/com/multi/fourtunes/model/configuration/SpringSecurityConfig.java, src/main/java/com/multi/fourtunes/model/controller/AIKeywordController.java, src/main/java/com/multi/fourtunes/model/controller/AdminpageController.java, src/main/java/com/multi/fourtunes/model/controller/CommunityController.java, src/main/java/com/multi/fourtunes/model/controller/KakaopayController.java, src/main/java/com/multi/fourtunes/model/controller/LoginController.java, src/main/java/com/multi/fourtunes/model/controller/NavController.java, src/main/java/com/multi/fourtunes/model/controller/PlayListController.java, src/main/java/com/multi/fourtunes/model/controller/TodayPickController.java, src/main/java/com/multi/fourtunes/model/controller/paging/InnerPagingController.java, src/main/java/com/multi/fourtunes/model/dao/CommunityDaoImpl.java, src/main/java/com/multi/fourtunes/model/dao/PlayListDaoImple.java, src/main/java/com/multi/fourtunes/model/dao/UserDaoImpl.java, src/main/java/com/multi/fourtunes/model/intercepter/SessionInvalidationInterceptor.java, src/main/java/com/multi/fourtunes/model/security/CustomAuthenticationSuccessHandler.java
=> Jung min apply logger
